### ISSUE TITLE
Fatal error: Class 'AttachmentBehavior' not found

### ISSUE THREAD

**Issue by louim** [milesj/uploader#110]
Hello!

I have tried to install the uploader plugin, but I always get the following error:

``` php
Fatal error: Class 'AttachmentBehavior' not found in /Users/lmcouture/Projets/mrc-bellechasse/admin/code/lib/Cake/Utility/ClassRegistry.php on line 156
```

I have followed installation as specified on you website, Installing composer, adding the composer.json file, and getting composer to install the project and its dependencies.

I also added the 

``` php
require_once dirname( __DIR__ ) . '/Vendor/autoload.php';
```

to the Config/core.php file as specified in the installation instructions.
I still get the same error.

**Comment by hardiksondagar** [comment]
I'm facing the same problem, can you share your composer.json file
