### ISSUE TITLE
transit problem

### ISSUE THREAD

**Issue by Aziza** [milesj/uploader#132]
thank you for this great plugin http://milesj.me/code/cakephp/uploader .
i use cakephp 2.2 and  running wamp  PHP 5.3.9
i have a problem  when I attempt to submit a file I get the following error.

Fatal Error

Erreur: Class 'Transit\Transit' not found
File: C:\wamp\www\asc-project\app\Plugin\Uploader\Model\Behavior\AttachmentBehavior.php
Line: 248

Attention: Si vous voulez personnaliser ce message d'erreur, créez app\View\Errors\fatal_error.ctp

i install the composer but i still unable to make this plugin work 
- Config/core.php.

require_once dirname(**DIR**) . '/Vendor/autoload.php';
- app/composer.json  :
  {
  "config": {
      "vendor-dir": "Vendor"
  },
  "require": {
      "mjohnson/uploader": "4._",
      "mjohnson/decoda": "6._"
  }
  }

can you help me 
I've been trying to get image uploads working for 2 days now with no success

**Comment by bkingg** [comment]
add this to your core.php at the top

require_once dirname(**DIR**) . '/Vendor/autoload.php';
